import { newDb } from 'pg-mem';
import { randomUUID } from 'node:crypto';
import { schemaStatements } from '../lib/schema.js';
const db = newDb();
db.public.registerFunction({ name: 'version', args: [], returns: 'text', implementation: () => 'pg-mem' });
const { Pool } = db.adapters.createPg();
const pool = new Pool();
const run = async (text, params = []) => (await pool.query(text, params)).rows;
for (const statement of schemaStatements) await run(statement);
await run(`update club_settings set opening_balance = $1 where id = 1`, [250]);
await run(`insert into donations (id, amount, donation_date, company_name, company_rep, notes) values ($1, $2, $3, $4, $5, $6)`, [randomUUID(), 1000, '2026-03-10', 'BNSF Railway', 'Jordan Lee', 'Spring sponsorship']);
await run(`insert into expenses (id, amount, expense_date, description, person_name, company_name, company_rep) values ($1, $2, $3, $4, $5, $6, $7)`, [randomUUID(), 125.5, '2026-03-12', 'Printing flyers', 'Danish Nadar', 'FedEx Office', null]);
const summary = (await run(`select * from club_financial_summary limit 1`))[0];
const ledger = await run(`select * from treasury_ledger order by activity_date desc, created_at desc`);
const donations = await run(`select * from donations`);
const expenses = await run(`select * from expenses`);
if (Number(summary.current_funds) != 1124.5 || ledger.length != 2 || donations.length != 1 || expenses.length != 1) throw new Error('Self-test failed.');
console.log('Self-test passed. Summary:', { openingBalance: Number(summary.opening_balance), totalGains: Number(summary.total_gains), totalExpenses: Number(summary.total_expenses), currentFunds: Number(summary.current_funds) });
console.log('Ledger entries:', ledger.length);
